### ISSUE TITLE
[BUG]: The images below About us section in home page are not "fit-to-screen"

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#404]
### Description

The images should be "fit-to-screen" for better visibility.

### Screenshots

![Screenshot 2024-11-07 214705](https://github.com/user-attachments/assets/cb47f817-f94d-4832-a898-9e4d09f1f93a)

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Research-Nexas/blob/DEV/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by trinetra110** [comment]
@Harshdev098 Please assign this issue to me and add 'gssoc-ext' and a 'level' labels to it.

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the CSS for images to ensure they fit the screen for better visibility. Added object-fit property to maintain aspect ratio while filling the container.

I also created pull request: https://github.com/Harshdev098/Research-Nexas/pull/405


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by trinetra110** [comment]
@Harshdev098 Please add the 'gssoc-ext' and a 'level' tag.
